import type { Metadata } from "next"
import { Nav } from "@/components/Nav"
import { Footer } from "@/components/Footer"
import { DocsToc } from "@/components/docs-toc"

export const metadata: Metadata = {
  title: "Privacy Policy — Wasit",
  description: "Privacy Policy for Wasit, an open-source protocol-compliance tester for the x402 and MPP protocols on Stellar.",
}

export default function PrivacyPage() {
  return (
    <>
      <Nav />
      <div className="wrap legal-page-wrap">
        <div className="legal-page-row">
          <div className="article-wrap">
            <article id="privacy-content" className="typeset legal-typeset">
            <h1>Privacy Policy</h1>
            <p><em>Last updated: September 2026.</em></p>

            <h2 id="scope">1. Scope</h2>
            <p>
              This policy covers two things: this documentation website
              (wasit.dev and its subpages), and the Wasit CLI, MCP server,
              and core library you install from npm. It doesn’t cover
              third-party services you point Wasit at while testing them —
              their own privacy policies apply to whatever data they
              collect.
            </p>

            <h2 id="this-website">2. This website</h2>
            <p>
              This site does not run analytics, does not set tracking
              cookies, and does not have user accounts or forms that
              collect personal information. The only data generated by
              visiting it is standard hosting-provider server logs (IP
              address, requested path, timestamp, user agent) collected by
              our host, Vercel, for operating and securing the platform —
              not by Wasit itself. See{" "}
              <a href="https://vercel.com/legal/privacy-policy" target="_blank" rel="noreferrer noopener">
                Vercel’s privacy policy
              </a>{" "}
              for details on that layer.
            </p>

            <h2 id="cli-mcp-server-core-library">3. The CLI, MCP server, and core library</h2>
            <p>
              Wasit runs on your own machine or infrastructure. It does not
              phone home, does not send telemetry to the maintainer, and
              does not collect usage analytics. When you run a check, it
              talks directly to the payment service and Stellar network
              endpoints you configure — those requests go where you point
              them, not through Wasit’s maintainer.
            </p>

            <h2 id="third-party-links">4. Third-party links</h2>
            <p>
              Pages here link out to GitHub, npm, X, and Stellar
              documentation. Once you follow one of those links, that
              site’s own privacy policy applies.
            </p>

            <h2 id="changes">5. Changes</h2>
            <p>
              If this policy changes in a way that matters, the date at
              the top of this page will be updated.
            </p>

            <h2 id="contact">6. Contact</h2>
            <p>
              Questions can be raised as an issue on{" "}
              <a href="https://github.com/wasit-dev/wasit" target="_blank" rel="noreferrer noopener">
                GitHub
              </a>{" "}
              or via{" "}
              <a href="https://x.com/wasithq" target="_blank" rel="noreferrer noopener">
                X
              </a>.
            </p>
            </article>
          </div>
          <DocsToc contentSelector="#privacy-content" className="legal-toc" />
        </div>
      </div>
      <Footer />
    </>
  )
}
